language: python
python:
  - 3.5
  - 3.6
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install "."
 # - pip install ABVitali/briscola
#addons
addons:
  sonarcloud:
    organization: "abvitali"
    token:
      secure: "gbPUZwaQ1S6dttSD9m1KzbgQaKlbuZsrwMJmm69sXNayLydTsym4RJeYtlAv467ub9i9VPJM0zOMbnc/UT2lOK1dCRILHsdWTl/++j07hp1tyxQzP8ZSbL1H1yFX1O5b6KjBXqclQk7pBN59n7cGdO3We9DHXa85ZONqTqKwtBw/8agd/Xj+JXiQQ8JstK+KdDY1OxmtiDQ/2e4LANAQqzVLlcsBaXAtk4269YfLno0MGza5H5Zv6mKT8O+idM4QcvwEqBSYQ3TRGjfH3QqxVmANo656YDYrNuLN9OiTPnhfRSRaxlJ4VptVV/Nq7dbt2QGkCdFeXth+dFdXqaBLQuKgVVKYZ8fR9XF+zPvxLoFPGz6qPxtjsvDVUjcqNNPDk1od+HE1EBEXdBW3uiyTbyzym82P+Y2z+uJYsX0TwlAXlZIxgqP0l+ais+JbLiJpHmA9Xx339Nl/mlWrXVy3GqPrgVOoJxiLbdiH8u/oaIbpv46xX5L1ORzzm2SlKjPX/ZxscfHDwpzrFq4tTZiIuRM5TwzbERnjsYEtE90sZeBS/yAGmb+3hRFr62zTlOM9kaBd1hyH3sohJNlYA9IItxAmHmIqriBCKy1JEuT9yUGK0KgDCxHzAmVwJcdLtLqu7iCF3kkkkduYLGvG1r6OYOdpxAyQTbKkH8LSI+6H+r4="
# command to run tests
script: 
  - ls -la
  - pytest
  - sonar-scanner -Dsonar.projectKey=ABVitali_briscola